//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mieszkania_domy
    {
        public string Pesel_w { get; set; }
        public string ID { get; set; }
        public Nullable<float> Metraz { get; set; }
        public string Miejscowosc { get; set; }
        public string Kod { get; set; }
        public string Adres { get; set; }
    
        public virtual Znajomi Znajomi { get; set; }
    }
}
