//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HurtowniaEntities : DbContext
    {
        public HurtowniaEntities()
            : base("name=HurtowniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mieszkania_domy> Mieszkania_domy { get; set; }
        public virtual DbSet<Znajomi> Znajomi { get; set; }
    
        [DbFunction("HurtowniaEntities", "Miejscowosc_mieszkanie")]
        public virtual IQueryable<Miejscowosc_mieszkanie_Result> Miejscowosc_mieszkanie(string miasto)
        {
            var miastoParameter = miasto != null ?
                new ObjectParameter("miasto", miasto) :
                new ObjectParameter("miasto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Miejscowosc_mieszkanie_Result>("[HurtowniaEntities].[Miejscowosc_mieszkanie](@miasto)", miastoParameter);
        }
    
        public virtual ObjectResult<PobierzZnajomych_Result> PobierzZnajomych(string imie)
        {
            var imieParameter = imie != null ?
                new ObjectParameter("Imie", imie) :
                new ObjectParameter("Imie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PobierzZnajomych_Result>("PobierzZnajomych", imieParameter);
        }
    
        public virtual ObjectResult<ProceduraMieszkanie_Result> ProceduraMieszkanie(string pesel)
        {
            var peselParameter = pesel != null ?
                new ObjectParameter("pesel", pesel) :
                new ObjectParameter("pesel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProceduraMieszkanie_Result>("ProceduraMieszkanie", peselParameter);
        }
    
        public virtual ObjectResult<szukanie_Result> szukanie(string wzorzec)
        {
            var wzorzecParameter = wzorzec != null ?
                new ObjectParameter("wzorzec", wzorzec) :
                new ObjectParameter("wzorzec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<szukanie_Result>("szukanie", wzorzecParameter);
        }
    }
}
