//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Znajomi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Znajomi()
        {
            this.Mieszkania_domy = new HashSet<Mieszkania_domy>();
        }
    
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Pesel { get; set; }
        public Nullable<System.DateTime> Data_urodzenia { get; set; }
        public Nullable<decimal> Majatek { get; set; }
        public string Miasto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mieszkania_domy> Mieszkania_domy { get; set; }
    }
}
